# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LASFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='WellProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectLocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lasfile',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWA.WellProject'),
        ),
    ]
