# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GWA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellproject',
            old_name='ProjectLocation',
            new_name='ProjectName',
        ),
    ]
