# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GWA', '0002_auto_20170703_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasfile',
            name='Project',
        ),
        migrations.DeleteModel(
            name='WellProject',
        ),
    ]
